---
dist: trusty
language: node_js
node_js:
  - "8.15"
# TODO untill https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-356362524
sudo: required

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache
    - $HOME/.yarn-cache

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - yarn install

before_script:
  - ./node_modules/.bin/eslint addon app tests

script:
  - ember test

notifications:
  email: false
  slack:
    rooms:
      - thinkhrcorp:OzWJSPvGAv25SzT6i0u5SyWh
    on_pull_requests: true
